// 
// healthItem.js
// 
//	-- corresponds to an entry in the healthItem table
//	-- properties: 
//		-- id,
//		-- accountId
//		-- traineeId  (to accommodate for any trainee not already in the DB)
//		-- date  (this is the date that the meal info is for; not neceesarily the created date of the record)
//		-- weight 
//		-- bodyfat 
//

var Limits = require('../constants.js').Limits;
var Utils = require('../util.js');

module.exports = function(sequelize, DataTypes) {

	return sequelize.define(
		//
		// model/table name
		//
		'healthItem',  
		//
		// model attributes/table columns (other than foreign keys and virtual ones)
		//
		{
			// id -- primary key, auto generated by sequelize

			// foreign keys: all added through the association defined in db.js
			// 		accountId -- foreign key to the account table, representing the account for the trainee
			
			date: {
				type: DataTypes.STRING,
				allowNull: false,
				validate: {
					isValidDate: function(value) {
						if (!Utils.isValidDate(value)) {
							throw new Error('Date is not in the \'yyyy-mm-dd\' format');
						}
					}
				}
				
			},
			// 斤
			weight: {
				type: DataTypes.FLOAT,
				allowNull: false,
				validate: {
					min: Limits.Weight.min,
					max: Limits.Weight.max
				}				
			},
			// %
			bodyfat: {
				type: DataTypes.FLOAT,
				allowNull: true,				
				validate: {
					min: Limits.Bodyfat.min,
					max: Limits.Bodyfat.max
				},
			} 
		}
	);
}